"""
qr/serializers.py

Serializers for the QRCode model (staff-facing API).

QRCodeSerializer:
    Serializes all relevant QRCode fields for the branch-manager endpoints:
      - id          (UUID, read-only — set at creation)
      - table_id    (UUID FK, read-only — the table this code is for, if any)
      - room_id     (UUID FK, read-only — the room this code is for, if any)
      - token       (UUID, read-only — generated by QRService)
      - is_active   (bool)
      - image_url   (URL string, read-only — set after R2 upload)
      - created_at  (ISO-8601 datetime, read-only)

Requirements: 14.1, 14.3
"""

from rest_framework import serializers

from apps.qr.models import QRCode


class QRCodeSerializer(serializers.ModelSerializer):
    """
    Full serializer for QRCode records.

    Read-only fields:
        id         — UUID PK, assigned at creation
        table_id   — UUID of the linked Table (null for room QR codes)
        room_id    — UUID of the linked Room (null for table QR codes)
        token      — UUID token encoded in the QR image; generated by QRService
        image_url  — Public URL of the rendered PNG stored in Cloudflare R2
        created_at — UTC creation timestamp

    The POST body accepted by QRCodeListCreateView accepts:
        {"table_id": "<uuid>"}  or  {"room_id": "<uuid>"}
    """

    table_id = serializers.UUIDField(source="table.id", read_only=True, allow_null=True)
    room_id = serializers.UUIDField(source="room.id", read_only=True, allow_null=True)

    class Meta:
        model = QRCode
        fields = [
            "id",
            "table_id",
            "room_id",
            "token",
            "is_active",
            "image_url",
            "created_at",
        ]
        read_only_fields = [
            "id",
            "token",
            "image_url",
            "created_at",
        ]
