# Generated by Django 5.0.9 on 2026-06-30 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_full_branch_table'),
        ('menus', '0002_alter_menuitem_dietary_tags'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, help_text='Auto-generated: BR<branch_id_short>-<YYYYMMDD>-<sequence>. Leave blank — populated automatically on first save.', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('received', 'Received'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('cancelled', 'Cancelled')], db_index=True, default='confirmed', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_anonymized', models.BooleanField(default=False, help_text='Set True by the nightly anonymization task; clears customer PII.')),
                ('placed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order value in branch currency at placement time.', max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='branches.branch')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='branches.table')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(help_text='Number of servings of this item in the order.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Snapshot of MenuItem.price at the moment this order was placed. Must not be updated after creation (Requirement 14.8).', max_digits=10)),
                ('special_instructions', models.TextField(blank=True, default='', help_text="Customer notes for preparation (e.g. 'extra spicy', 'no nuts').")),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menus.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
    ]
