# Generated by Django 5.0.9 on 2026-06-29 16:41

import shared.storage
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whitelabel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, storage=shared.storage.R2Storage(), upload_to='logos/')),
                ('primary_color', models.CharField(help_text='Hex colour code, e.g. #3B82F6', max_length=7)),
                ('secondary_color', models.CharField(help_text='Hex colour code, e.g. #F59E0B', max_length=7)),
                ('font_choice', models.CharField(default='default', max_length=50)),
                ('custom_domain', models.CharField(blank=True, max_length=200)),
                ('favicon', models.ImageField(blank=True, null=True, storage=shared.storage.R2Storage(), upload_to='favicons/')),
                ('qr_design_template', models.CharField(default='default', max_length=50)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('currency_format', models.CharField(default='{symbol}{amount}', max_length=20)),
                ('timezone', models.CharField(default='Africa/Addis_Ababa', max_length=50)),
                ('date_format', models.CharField(default='%d/%m/%Y', max_length=30)),
                ('time_format', models.CharField(default='%H:%M', max_length=30)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('tax_label', models.CharField(default='VAT', max_length=30)),
                ('service_charge_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('table_number_prefix', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Tenant Configuration',
            },
        ),
    ]
