# Generated by Django 5.0.9 on 2026-06-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0002_alter_domain_domain_alter_domain_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_branches', models.PositiveIntegerField(help_text='Maximum number of branches a tenant on this plan may create.')),
                ('max_menu_items', models.PositiveIntegerField(help_text='Maximum total menu items across all branches.')),
                ('max_staff_accounts', models.PositiveIntegerField(help_text='Maximum number of active staff accounts across all branches.')),
                ('feature_flags', models.JSONField(default=dict)),
                ('price_etb', models.DecimalField(decimal_places=2, help_text='Monthly subscription price in Ethiopian Birr (ETB).', max_digits=10)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price_etb'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('overdue', 'Overdue')], db_index=True, default='active', max_length=20)),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Subscription',
                'verbose_name_plural': 'Tenant Subscriptions',
                'ordering': ['-current_period_start'],
            },
        ),
    ]
