# Generated by Django 6.0.6 on 2026-07-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_room_model'),
        ('qr', '0003_verify_qrcode_token_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='branches.room'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True for the most-recently generated QR code for this location. Older codes are set to False by QRService.generate_qr.'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='branches.table'),
        ),
    ]
