# Generated by Django 6.0.6 on 2026-07-05 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_domain_domain_alter_domain_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=10)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'platform audit log',
                'verbose_name_plural': 'platform audit logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'action'], name='plat_audit_log_ts_action_idx')],
            },
        ),
    ]
