# Generated by Django 5.0.9 on 2026-07-05 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0004_room_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("secret", models.CharField(max_length=64)),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of subscribed event types, e.g. ['order.created', 'order.status_changed']",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_configs",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Configuration",
                "verbose_name_plural": "Webhook Configurations",
                "ordering": ["-created_at"],
            },
        ),
    ]
