# Generated by Django 5.0.9 on 2026-06-30 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_full_branch_table'),
        ('financials', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('order', 'Order'), ('event', 'Event'), ('catering', 'Catering'), ('other', 'Other')], default='order', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='branches.branch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='orders.order')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income Records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'date'], name='financials__branch__441d87_idx'), models.Index(fields=['branch', 'source'], name='financials__branch__25eafc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfitRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_records', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Profit Record',
                'verbose_name_plural': 'Profit Records',
                'ordering': ['-period_start'],
                'unique_together': {('branch', 'period_type', 'period_start')},
            },
        ),
    ]
