# Generated by Django 6.0.6 on 2026-07-05 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_full_branch_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Room identifier (e.g. 'VIP Room 1', 'Private Dining').", max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Maximum number of guests this room can seat.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
                'unique_together': {('branch', 'name')},
            },
        ),
    ]
