# Generated by Django 5.0.9 on 2026-06-30 15:36

import django.core.validators
import django.db.models.deletion
import shared.storage
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_full_branch_table'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('food_purchases', 'Food Purchases'), ('staff_salaries', 'Staff Salaries'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('transportation', 'Transportation'), ('miscellaneous', 'Miscellaneous')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_incurred', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, storage=shared.storage.R2Storage(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date_incurred', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'date_incurred'], name='expenses_ex_branch__6526c8_idx'), models.Index(fields=['branch', 'category'], name='expenses_ex_branch__e8e045_idx')],
            },
        ),
    ]
