# Generated by Django 5.0.9 on 2026-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dietary_tags',
            field=models.JSONField(blank=True, default=list, help_text='List of dietary tag strings. Valid values: vegetarian, vegan, gluten_free, dairy_free, halal, low_carb, keto, high_protein, spicy, seafood, desserts, beverages, childrens_meals'),
        ),
    ]
