# Generated by Django 5.0.9 on 2026-07-02 19:13

import shared.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_alter_menuitem_dietary_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="external_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Cloudinary or other CDN URL for the menu item image",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Local/R2 file upload (used when R2 is configured)",
                null=True,
                storage=shared.storage.R2Storage(),
                upload_to="menu_items/",
            ),
        ),
    ]
