# Generated by Django 5.0.9 on 2026-07-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_add_external_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_am",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Amharic translation of the category name.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="description_am",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Amharic translation of the description.",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="name_am",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Amharic translation of the menu item name.",
                max_length=200,
            ),
        ),
    ]
